name: w3c-validator
on: pull_request

jobs:
  w3c-validator:
    name: Validate files
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run Validator
        uses: bucherfa/w3c-validator-action@v0.2
        
